### ISSUE TITLE
Add tutorial or at least some examples

### ISSUE THREAD

**Issue by ChShersh** [mrkkrp/modern-uri#1]
For person who never worked previously with `uri` or `uri-bytestring` or Haskell beginner it's not very easy to understand how to use `modern-uri` package and why one should do it.

**Comment by mrkkrp** [comment]
A tutorial certainly won't hurt. I just wanted to release this faster because I need this package for another project, so tutorial is pending.

**Comment by mrkkrp** [comment]
Just added a "Getting started" section to the readme.
