### ISSUE TITLE
Use newtypes instead of `RText`

### ISSUE THREAD

**Issue by mitchellwrosen** [mrkkrp/modern-uri#11]
Hi, would you accept a patch that replaces the `RText` machinery with a bunch of newtypes? i.e.

```haskell
newtype Scheme = Scheme { unScheme :: Text }
newtype Host = Host { unHost :: Text }
... etc ...
```

I think it would make the library a bit friendlier to beginners :)

**Comment by mrkkrp** [comment]
> I think it would make the library a bit friendlier to beginners :)

Maybe, but at this point I'd rather prefer to keep the API stable than to change it. The current approach allows a bit nicer organization of code and a single `unRText` function for unwrapping. I'm not entirely convinced that indexing by types obtained with `DataKinds` vs simple newtypes makes a big difference for beginners.

**Comment by mitchellwrosen** [comment]
Sounds good. I'll close this issue out.
