### ISSUE TITLE
A URI with a Query such as '?&height=500&width=500' cannot be parsed

### ISSUE THREAD

**Issue by etorreborre** [mrkkrp/modern-uri#16]
It seems that it is rejected [here](https://github.com/mrkkrp/modern-uri/blob/88321014f8384c50bc3c831f9b3ac735871cf97c/Text/URI/Parser/Text.hs#L128) but I can't find in the standard, nor with online URI validators why such a query string should be rejected. Context: I really have real-life queries like this in my data...

**Comment by mrkkrp** [comment]
It looks like this should indeed be allowed. Can you fix it and open a PR?

**Comment by etorreborre** [comment]
Yes, I'll try to do it over the week-end thanks
