### ISSUE TITLE
Expose parsers of certain classes of URIs

### ISSUE THREAD

**Issue by Ericson2314** [mrkkrp/modern-uri#19]
e.g. for absolute URIs only, etc. One can always validate after the fact, but that is potentially less efficient. Might be easier to add a `Parser` or `Internal` module exposing all the bits for people to make their own sub parsers.

CC @luigy

**Comment by mrkkrp** [comment]
I don't know, I think it's best to analyze after the fact and then report a custom failure pointing to beginning of URI. Proliferation of parsers for concrete cases doesn't sound good to me.

**Comment by Ericson2314** [comment]
Well, individual parsers for URI components matching nonterminals from the RFC avoids the combinatorial explosion.

**Comment by mrkkrp** [comment]
Then the user must know how to combine these sub-parsers, which means he/she must know stuff that should be abstracted by the library. I myself now don't remember subtleties of URI parsing, as a user I'd want things to stay simple to use and understand.

That said, if you need this, then we could create an "internal" module or two with almost anything you like. PRs are welcome.

**Comment by Ericson2314** [comment]
I took a look https://tools.ietf.org/html/rfc3986. Wow, things look complicated. (Not sure if it's so because there's lots of intrinsic edge cases, or because of how they tweaked the grammer for sake of parser efficiency.) I guest post-hoc validation is fine for now :).

**Comment by mrkkrp** [comment]
Closing for now then.
