### ISSUE TITLE
Port numbers validation

### ISSUE THREAD

**Issue by alexfmpe** [mrkkrp/modern-uri#28]
I don't see any limitations on port numbers in https://tools.ietf.org/html/rfc3986 itself, but I'd expect parsing to fail when port numbers are `>= 2^16`, at least for the schemes that declare ports to be 16-bit numbers. Is this a bug?

```haskell
> mkURI "http://localhost:65535"
URI {uriScheme = Just "http", uriAuthority = Right (Authority {authUserInfo = Nothing, authHost = "localhost", authPort = Just 65535}), uriPath = Nothing, uriQuery = [], uriFragment = Nothing}

> mkURI "http://localhost:65536"
URI {uriScheme = Just "http", uriAuthority = Right (Authority {authUserInfo = Nothing, authHost = "localhost", authPort = Just 65536}), uriPath = Nothing, uriQuery = [], uriFragment = Nothing}

> mkURI "http://localhost:65536000"
URI {uriScheme = Just "http", uriAuthority = Right (Authority {authUserInfo = Nothing, authHost = "localhost", authPort = Just 65536000}), uriPath = Nothing, uriQuery = [], uriFragment = Nothing}
```

**Comment by mrkkrp** [comment]
I don't have an option on this. If it's not against the spec, then it's probably not a bug. Still, may be a surprising behavior.

**Comment by alexfmpe** [comment]
I can't figure out if the spec is to be interpreted as "we impose that all schemes can not impose port number restrictions" or "we impose nothing for all schemes and defer to per-scheme restrictions", but I'd lean towards the later, because it's what happens in practice.

**Comment by mrkkrp** [comment]
> we impose nothing for all schemes and defer to per-scheme restrictions

Then it means that it is not a bug in `modern-uri`, right?

**Comment by alexfmpe** [comment]
Right.
I was expecting a behavior along the lines of
`mkURI = mkRFC3986 >=> mkRFCScheme`
but I guess it really does needs to be
`mkURI = mkRFC3986`
or it'd have to know every scheme ever.

I guess what I want is `mkTcpURI`, `mkHttpURI`, etc. 
Does it make sense to have those in this repo/package?

**Comment by mrkkrp** [comment]
Just for the sake of part validation, I'd say no.
