### ISSUE TITLE
Compatibility with bytestring 0.11

### ISSUE THREAD

**Issue by sjakobi** [mrkkrp/modern-uri#36]
The latest `modern-uri` release is one of the few packages that doesn't build with `bytestring-0.11.0.0`, not even with `--allow-newer`. I see that you've already fixed the issue in https://github.com/mrkkrp/modern-uri/commit/794342654d3350da792c1b07cf53b3d84adcb32a#diff-008cf87a8b382cac22984446b6a6a3587d4994a8df780cf3d174f8ca2aff5c10. Could you make a release?! Thanks!

**Comment by mrkkrp** [comment]
Thanks for the heads up! Published 0.3.3.1 on Hackage.

**Comment by sjakobi** [comment]
Cheers! :)
