### ISSUE TITLE
Trailing slashes for URLs with no path

### ISSUE THREAD

**Issue by moll** [mrkkrp/modern-uri#37]
Hey,

Thanks for maintaining URI!

Is it intentional that a URI representing `http://example.com` (e.g. when parsed with `mkURI`) is rendered as `http://example.com/`? I find the trailing slashes a little ugly when showing URLs to people.

Cheers

**Comment by mrkkrp** [comment]
I pushed a fix for this. I'm also going to publish a new version, 0.3.4.0.

**Comment by moll** [comment]
Ah, that's brilliant. Thank you!
