### ISSUE TITLE
Bug parsing numeric subdomains

### ISSUE THREAD

**Issue by bitc** [mrkkrp/modern-uri#46]
This gives weird behaviour:

```haskell
> mkURI "https://104.155.144.4.sslip.io:443/"
```

The host gets chopped and half of it along with the port end up in the `uriPath`:

```haskell
URI {
  uriScheme = Just "https",
  uriAuthority = Right (Authority {authUserInfo = Nothing, authHost = "104.155.144.4", authPort = Nothing}),
  uriPath = Just (True,".sslip.io:443" :| []),
  uriQuery = [],
  uriFragment = Nothing
}
```

I think it may be true that according to some RFCs there shouldn't be numbers in subdomains, but in practice these types of domains exist and work fine everywhere.

In any case, when I roundtrip the current result we get back the following, which is different than the original:

```haskell
> render uri
"https://104.155.144.4/.sslip.io%3a443/"
```

Btw the example url I am using is a real url, part of the [sslip.io](https://sslip.io) service: https://104.155.144.4.sslip.io:443/

Thank you

**Comment by mrkkrp** [comment]
I think the problem here is not digits per se, but the fact that they form something that looks like an IP number. Therefore it gets parsed as an IP number and then the rest of the parser has to deal with the leftovers. I'll look what can be done.
