### ISSUE TITLE
`mkURI`  fails to correctly parse uri when hostname contains a "_"

### ISSUE THREAD

**Issue by aloussase** [mrkkrp/modern-uri#73]
Is this the expected behavior?

![image](https://github.com/mrkkrp/modern-uri/assets/84427521/9ea13fc8-aaf5-4dbb-8cd9-94fea5be2f65)

I might be missing something, but the hostname of that uri is auth_service. `mkURI` seems to be splitting it at the underscore for some reason.

Here is a screenshot showing it correctly handles the uri when I replace `auth_service` with `auth-service`:

![image](https://github.com/mrkkrp/modern-uri/assets/84427521/928cad93-6d49-4493-b96a-6bca8d5a023d)

**Comment by mrkkrp** [comment]
Thanks for the report! `modern-uri-0.3.6.1` with the fix is now on Hackage.

**Comment by aloussase** [comment]
Thanks for the quick fix!
