### ISSUE TITLE
Empty path with a trailing slash

### ISSUE THREAD

**Issue by belka-ew** [mrkkrp/modern-uri#78]
I don't see a way to represent an URLs with the trailing slash only in the path, e.g. https://example.com/. Parsing these URLs and rendering them gives different results, so the following 2 tests fail:

```hs
    it "1" $
      render [QQ.uri|https://example.com/|] `shouldBe` "https://example.com/"
    it "2" $
      let given = "https://example.com/"
       in (render <$> mkURI given) `shouldBe` Just given
```

If `uriPath` is `Nothing` I can't specify whether I want a trailing slash or not. Otherwise, I can't give an empty path since path pieces are a `NonEmpty` list.

**Comment by mrkkrp** [comment]
The library performs some normalization, and this is an instance of that. I'd rather ask what does elimination of the trailing slash break in your case?

**Comment by belka-ew** [comment]
Nothing serious. I was writing a program which generates text files with linux package information. And one part of this information is the homepage URL. And the convention there is in many cases to use the trailing slash in these files.

I just saw that there is support for a trailing slash in `uriPath` and wondered why this doesn't work with an empty path. But after some thinking, paths with and without a trailing slash are different; but if the path is missing, it's probably the same as `/`. And the README actually mentions the normalization.
